services:
  ysyry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://ysyry-api.vectrapy.com/api}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://ysyry.com.py}
    container_name: ysyry_app
    restart: unless-stopped
    ports:
      - "7074:7074"
    environment:
      - NODE_ENV=production
      - PORT=7074
      - HOSTNAME=0.0.0.0
